name: Test and Release

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  actions: write

env:
  CI: 1

jobs:
  test:
    runs-on: ubuntu-22.04

    timeout-minutes: 60

    environment: ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install sharp
        run: cd layers/sharp/nodejs && npm ci && cd ../../..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE}}
          role-session-name: github-action-serverless-aws-training
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check Typescript
        run: npx tsc

      - name: Generate Stack ID
        run: |
          RANDOM_STRING=`node -e "const crypto = require('crypto'); process.stdout.write(crypto.randomBytes(Math.ceil(8 * 0.5)).toString('hex').slice(0, 8));"`
          echo "STACK_NAME=ppr-${RANDOM_STRING}" >> $GITHUB_ENV

      - name: Run Unit Tests
        run: npm test

      - name: Deploy solution stack
        run: npx cdk deploy ${{ env.STACK_NAME }} --require-approval never

      - name: Run End-to-End Tests
        run: npm run test:e2e

      - name: Clean up End-to-End test resources
        if: always()
        run: |
          ./cli.sh purge-bucket-objects
          npx cdk destroy -f ${{ env.STACK_NAME }}

  release:
    needs:
      - test
    runs-on: ubuntu-22.04

    if: github.ref == 'refs/heads/saga'

    environment: ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Trigger release workflow
        if: steps.semantic-release.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh workflow run cd.yml
